# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

baseURL: "/"
relativeURLs: true

title: "Corpus Vasorum Antiquorum, Fascicule 10"
languageCode: "en-us"
theme: "quire-starter-theme"
publishDir: site

footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"
googleAnalytics: ""

pluralizeListTitles: true
disableKinds:
  - "home"
  - "section"
  - "taxonomy"
  - "taxonomyTerm"

blackfriday:
  fractions: false
  hrefTargetBlank: true

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  licenseIcons: true
  pageLabelDivider: ". "
  citationPageLocationDivider: ", "
  displayBiblioShort: true
  imageDir: "img"
  tocType: full
  menuType: full
  prevPageButtonText: "Back"
  nextPageButtonText: "Next"
  entryPageSideBySideLayout: true
  entryPageObjectLinkText: "View in Collection"
  figureLabelLocation: below # below | on-top
  figureModal: false
  figureModalIcons: true
  figureZoom: true
  frontmatterPageStart: 0
  bodyPageStart: 100
  backmatterPageStart: 300
