[build]
publish = "site"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build"

[context.split1.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"

[context.deploy-preview]
publish = "publications/cva10/"
command = "npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.48"

[context.branch-deploy]
command = "npm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.48"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
